#
# Makefile for the linux ramfs routines.
#

obj-y += crfs.o crfs_security.o crfs_mem.o \
	 crfs_pmfs_balloc.o crfs_inode.o crfs_pmfs_xip.o inode.o persist.o wprotect.o journal.o dir.o file.o bbuild.o \
	 symlink.o namei.o ioctl.o crfs_super.o crfs_scheduler.o crfs_scalability.o crfs_stat.o

#obj-y += crfs_kerntest.o snappy.o

#crfs-y  += crfs_journal.o crfs_security.o
#crfs-y  += crfs_security.o
#pmfs-$(CONFIG_PMFS_WRITE_PROTECT) += wprotect.o
#pmfs-$(CONFIG_PMFS_XIP) += xip.o
