language: c
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y uuid-dev valgrind
  - cp src/test/testconfig.sh.example src/test/testconfig.sh
script: make cstyle && make && make test && make check
